[platformio]
description = Water Level and Temperture Monitoring System
[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

board_build.filesystem = littlefs
board_build.partitions = huge_app.csv

lib_deps =
    marcoschwartz/LiquidCrystal_I2C
    adafruit/Adafruit ADXL345
    adafruit/Adafruit MAX31865 library

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DARDUINO_ENABLE_PERIPHERAL_MANAGER=1
